test:
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - apt-get update -qy
  - apt-get install -y python-dev python3-pip
  - pip install -r requirements.txt
  - bash selftest
